#!/bin/bash
# POSIX

attach=0

while :; do
    case $1 in
        -a|-\?|--attach)
            attach=1
            ;;
        -?*)
            printf 'Warning: Unknown option: %s\n' "$1" >&2
            ;;
        *) #default case: no more options
            break
    esac

    shift
done

if [ "$attach" -eq "0" ]; then
    docker rm amuse 2> /dev/null
    if [ $? -ne 0 ]; then
        printf 'Container already exists. Trying to attach...\n'
    else 
        docker run --name amuse -p 80:80 -it amuse /bin/bash -c 'sudo service nginx start; ./init-all.sh start; bash'
        exit
    fi
fi

docker exec -it amuse /bin/bash
