version: '3.4'
services:
  app:
    image: rojen/amusewiki:amusewiki-git
    volumes:
      - './repo:/var/lib/amusewiki/repo'
      - './thumbnails:/var/lib/amusewiki/thumbnails'
      - './db/sqlite.db:/var/lib/amusewiki/sqlite.db'
      - './db/dbic.yaml:/var/lib/amusewiki/dbic.yaml'
