#!/bin/bash

sudo nginx -s stop &>/dev/null
sudo chown -R amusewiki:amusewiki \
	/var/lib/amusewiki/repo \
	/var/lib/amusewiki/thumbnails \
	/var/lib/amusewiki/*.yaml \
	/var/lib/amusewiki/*.db \
	/var/lib/dbconfig-common/sqlite3/amusewiki \
	&>/dev/null &
post-domain.sh &>/dev/null
post-nginx.sh &>/dev/null
post-password.sh &>/dev/null &
sudo nginx &>/dev/null
amusewiki-upgrade-db &>/dev/null &

amusewiki-jobber-exec "$@"
