#!/bin/bash

sudo nginx -s stop &>/dev/null
sudo chown -R amusewiki:amusewiki /var/lib/amusewiki &>/dev/null
post-domain.sh &>/dev/null
post-nginx.sh &>/dev/null
post-password.sh &>/dev/null
sudo nginx &>/dev/null
amusewiki-upgrade-db &>/dev/null &

amusewiki-jobber-exec "$@"
