services:
  app:
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
      args:
        AMUSE_BUILD_DOMAIN: amusewiki.localdomain
        AMUSE_CLONE_COMMAND: 'git clone https://github.com/melmothx/amusewiki.git /var/lib/amusewiki'
        AMW_WORKERS: 5
        AMW_NPROC: 5
        AMW_USERNAME: amusewiki
        AMW_PASSWORD: changeme
        AMW_SQLITE_PATH: /var/lib/dbconfig-common/sqlite3/amusewiki/amusewiki
    volumes:
      - './amusewiki/repo:/var/lib/amusewiki/repo'
      - './amusewiki/thumbnails:/var/lib/amusewiki/thumbnails'
      - './amusewiki/staging:/var/lib/amusewiki/staging'
      - './amusewiki/db:/var/lib/dbconfig-common/sqlite3/amusewiki'
      - './amusewiki/nginx:/etc/nginx/sites-enabled'
    env_file: lib/container.env
