version: '3.8'
services:
  app:
    # texlive-base and texlive-full not supported due to size
    image: rojen/amusewiki:package
    environment:
      #- PWD_HOST_FQDN=${PWD_HOST_FQDN}
      - PWD_HOST_FQDN=labs.play-with-docker.com
      - SESSION_ID=${SESSION_ID}
      - CONTAINER_IS_IN_PWD=true
      - PWD_PORT=80 # change to 443 if you want to use https
      - AMW_WORKERS=5
      #- CHANGE_PASSWORD_BEFORE_RUN=true
      #- AMW_USERNAME=amusewiki
      #- AMW_PASSWORD=changeme
    ports:
      - 80:80 # change to 443:443 if you want to use https
