name: rojen/amusewiki:texlive-full

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build the Docker image
      run: docker build texlive-full/ --file texlive-full/Dockerfile --tag rojen/amusewiki:texlive-full --build-arg AMUSE_BUILD_DOMAIN=amusewiki.localdomain --build-arg AMUSE_CLONE_COMMAND='git clone https://github.com/melmothx/amusewiki.git /var/lib/amusewiki'

    - name: Docker Push
      run: docker push rojen/amusewiki:texlive-full
